version: "3"
services:

  # using rds now
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=camerondalton

  nginx:
    image: ccronheimer/codemates_nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"

  api:
    image: ccronheimer/codemates_api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RDS_HOSTNAME=aa1kppeuyyybx3a.c7kvypav9ocr.us-east-1.rds.amazonaws.com
      - RDS_USERNAME=postgres
      - RDS_PASSWORD=camerondalton
      - RDS_PORT=5432
      - RDS_DB_NAME=ebdb

  client:
    stdin_open: true
    image: ccronheimer/codemates_client
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API=http://localhost:80/api/v1/code
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
